## 1. Run the following:

In [13]:
import numpy as np
a = np.array([1, 2, 3])
print(type(a))
print("Matrix Shape of a:",a.shape)
print("Values in that Index:",a[0], a[1], a[2])
a[0] = 5
print(a)
rank=np.linalg.matrix_rank(a)
print("Rank Of the Matrix:",rank)

<class 'numpy.ndarray'>
Matrix Shape of a: (3,)
Values in that Index: 1 2 3
[5 2 3]
Rank Of the Matrix: 1


## 2. Run the following:

In [17]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix Of B:",b)
print("Shape of Matrix B:",b.shape)
print("Values with indexing:",b[0,0],b[0,1],b[1,0])
rank=np.linalg.matrix_rank(b)
print("rank of b:",rank)

Matrix Of B: [[1 2 3]
 [4 5 6]]
Shape of Matrix B: (2, 3)
Values with indexing: 1 2 4
rank of b: 2


## 3. Numpy also provides many functions to create arrays. Assign the correct comment to each of the

In [23]:
a=np.zeros((2,2))
b=np.ones((1,2))
c=np.full((2,2), 7)
d=np.random.random((2,2))
e=np.eye(2)
print("value of a:", a, "\nValue of b:", b, "\nvalue of c:", c, "\nvalue of d:", d, "\nvalue of e:", e)

value of a: [[0. 0.]
 [0. 0.]] 
Value of b: [[1. 1.]] 
value of c: [[7 7]
 [7 7]] 
value of d: [[0.65838783 0.74451317]
 [0.65705225 0.61526157]] 
value of e: [[1. 0.]
 [0. 1.]]


## 4. Run the following

In [37]:
a=np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print("shape of A:",a.shape)
b=a[:2, 1:3]
print("shape of B",b.shape)
print("Values in B",b)


shape of A: (3, 4)
shape of B (2, 2)
Values in B [[2 3]
 [6 7]]


## 5.(a) A slice of an array is a view into the same data. Follow the comments in the following snippet 

In [38]:
print("Value Before Modification:",a[0, 1])

Value Before Modification: 2


## 5.(b) What does the last line print? Does modifying b modify the original array?

In [39]:
b[0, 0] = 77
print("Modifyed B:",a[0, 1])

Modifyed B: 77


## 6 What are the values and shapes of col r1 and col r2?

In [49]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[1, :]
row_r2 =a[1:2,:]
print("Row Values Of r1:",row_r1,"\n Row shape of r1:",row_r1.shape)
print("Row Values Of r2:",row_r2,"\n Row shape of r2:",row_r2.shape)
col_r1=a[:,1]
col_r2=a[:,1:2]
print("col Values Of r1:",col_r1,"\n Colshape of r1:",col_r1.shape)
print("Col Values Of r2:",col_r2,"\n Col shape of r2:",col_r2.shape)

Row Values Of r1: [5 6 7 8] 
 Row shape of r1: (4,)
Row Values Of r2: [[5 6 7 8]] 
 Row shape of r2: (1, 4)
col Values Of r1: [ 2  6 10] 
 Colshape of r1: (3,)
Col Values Of r2: [[ 2]
 [ 6]
 [10]] 
 Col shape of r2: (3, 1)


## 7 Are the two printed arrays equivalent?

In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))


[1 4 5]
[1 4 5]


## 8 Are the two printed arrays equivalent?

In [59]:
a = np.array([[1,2], [3, 4], [5, 6]])
b = a[[0, 0], [1, 1]]
print("Values of B:", b)
c = np.array([a[0, 1], a[0, 1]])
print("Values of C:", c)

Values of B: [2 2]
Values of C: [2 2]


## 9. One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix.

In [63]:
a=np.array([[1,2,3],[4,5,6], [7,8,9], [10, 11, 12]])
print("Values Of A:",a)
b=np.array([0, 2,0, 1])
print("Values Of B:",b)
print("Picked Values:",a[np.arange(4), b])
a[np.arange(4),b] += 10
print("Values of After:",a )


Values Of A: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
Values Of B: [0 2 0 1]
Picked Values: [ 1  6  7 11]
Values of After: [[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


## 10. Run the following

In [66]:
a=np.array([[1,2], [3, 4], [5, 6]])
bool_idx=(a>2)
print("Values Of bool_idx:",a[bool_idx])
print("shape Of bool_idx:",a[bool_idx].shape)
print("Values Of:",a[a>2])
print("Shape Of:",a[a>2].shape)


Values Of bool_idx: [3 4 5 6]
shape Of bool_idx: (4,)
Values Of: [3 4 5 6]
Shape Of: (4,)


## 11.What are the datatypes of x, y, z?

In [68]:
x = np.array([1, 2])
print("Data Type Of X:",x.dtype)
y = np.array([1.0, 2.0])
print("Data Type Of Y:",y.dtype)
z = np.array([1, 2], dtype=np.int32)
print("Data Type Of Z:",z.dtype)

Data Type Of X: int64
Data Type Of Y: float64
Data Type Of Z: int32


## 12. Give the output for each print statement in the following code snippet

In [73]:
x=np.array([[1,2],[3,4]],dtype=np.float64)
y=np.array([[5,6],[7,8]],dtype=np.float64)
print("Addition of:",x+y)
print("Addition of:",np.add(x,y))
print("Subtraction of:",x-y)
print("Subtraction of:",np.subtract(x,y))
print("Multipliction of:",x*y)
print("Multipliction of:",np.multiply(x,y))
print("Divison of:",x/y)
print("Divison of:",np.divide(x,y))
print("Squares of:",np.sqrt(x))

Addition of: [[ 6.  8.]
 [10. 12.]]
Addition of: [[ 6.  8.]
 [10. 12.]]
Subtraction of: [[-4. -4.]
 [-4. -4.]]
Subtraction of: [[-4. -4.]
 [-4. -4.]]
Multipliction of: [[ 5. 12.]
 [21. 32.]]
Multipliction of: [[ 5. 12.]
 [21. 32.]]
Divison of: [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Divison of: [[0.2        0.33333333]
 [0.42857143 0.5       ]]
Squares of: [[1.         1.41421356]
 [1.73205081 2.        ]]


## 13 What are the mathematical operations performed by the last two instructions?

In [ ]:
v=np.array([9,10])
w=np.array([11, 12])
print(v.dot(w))
print(np.dot(v, w))

219
219


In [75]:
x = np.array([[1,2],[3,4]])
print(x.dot(v))
print(np.dot(y, v))

[29 67]
[105. 143.]


## 15 Can you write the same code for the product of y with x?

In [80]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6,7],[7,8,9]])
print(np.dot(x, y))
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[19 22 25]
 [43 50 57]]
10
[4 6]
[3 7]


## 16 What is the transpose of x? How is it different from x?

In [82]:
x = np.array([[1,2,3], [3,4,5]])
print("Value ofx:",x)
print("transpose of X:",x.T)

Value ofx: [[1 2 3]
 [3 4 5]]
transpose of X: [[1 3]
 [2 4]
 [3 5]]


## 17 Complete the following code in order to add the vector v to each row of a matrix x:

In [95]:
x=np.array([[1,2,3],[4,5,6], [7,8,9], [10, 11, 12]])
v=np.array([1,0,1])
y=np.zeros(x.shape)
for i in range(x.shape[0]):
    for j in range(x.shape[1]):
        y[i,j]=x[i,j]+v[j]
print("Result Of:",y)





Result Of: [[ 2.  2.  4.]
 [ 5.  5.  7.]
 [ 8.  8. 10.]
 [11. 11. 13.]]


## 18 The previous solution works well; however when the matrix x is very large, computing an explicit loop in Python could be slow. An alternative is to use tile. Run the following and interpret the result

In [99]:
vv = np.tile(v, (4, 1))
print(vv)
x=np.array([[1,2,3],[4,5,6], [7,8,9], [10, 11, 12]])
v=np.array([1,0,1])
y=np.zeros(x.shape)
vv = np.tile(v, (x.shape[0], 1))
y = x + vv
print("Final Result:",y)


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
Final Result: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


## 19

In [118]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1,0,1])
y = x + v
print("Value Of Y:", y)
v = np.array([1,2,3])
w = np.array([4,5])
r = v.reshape(1, 3)
print("Reshape Result Of v:", r)


Value Of Y: [[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
Reshape Result Of v: [[1 2 3]]


## 20

In [119]:
x1 = np.array([[1,2,3], [4,5,6]])
print("X1 Value:",x1)
y1 = x1 + r
print("adding v to each row of x:",y1)

X1 Value: [[1 2 3]
 [4 5 6]]
adding v to each row of x: [[2 4 6]
 [5 7 9]]


## 21

In [120]:
y2 = x1 + w.reshape(2, 1)
print("adding w to each column of x:", y2)

adding w to each column of x: [[ 5  6  7]
 [ 9 10 11]]


## 22

In [121]:
y = x1 * 2 
print("Multiply X with 2 is:",y)

Multiply X with 2 is: [[ 2  4  6]
 [ 8 10 12]]
