In [1]:
import numpy as np

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
# To select rows 1 to 2 (inclusive of 1, exclusive of 2) and columns 0 and 2:
arr1[1:3,0:2]
arr1[0:2,0:2]
arr1[0:2,1:3]
arr1[1:3,1:3]

array([[5, 6],
       [8, 9]])